server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUri:
      defaultZone: http://${APP_SERVER_HOST}:8761/eureka

logging:
  file:
    name: logs/api-gateway.log