server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-gateway
          uri: lb:http://API-GATEWAY
          predicates:
            - Path=/api/v1/gateway/**
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
  data:
    redis:
      host: ${APP_SERVER_HOST}
      port: ${SESSION_DB_PORT}
  session:
    redis:
      flush-mode: immediate
      namespace: spring:session
      repository-type: default
    timeout: 60m

eureka:
  client:
    serviceUri:
      defaultZone: http://${APP_SERVER_HOST}:8761/eureka

logging:
  file:
    name: logs/api-gateway.log