server:
  port: 8001

spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DATABASE_NAME}
      authentication-database: admin

eureka:
  client:
    serviceUri:
      defaultZone: http://${APP_SERVER_HOST}:8761/eureka

logging:
  file:
    name: logs/task-service.log
  level:
    com.nturbo1.task_service: debug