server:
  port: 8000

spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DATABASE_NAME}
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://${APP_SERVER_HOST}:8761/eureka

mongock:
  migration-scan-package: com.nturbo1.user_service

logging:
  file:
    name: logs/user-service.log
  level:
    com.nturbo1.user_service: debug

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html

openapi:
  service:
    title: ${spring.application.name} doc
    version: 1.0.0
    url: http://${APP_SERVER_HOST}:8222