server:
  port: 8000

spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DATABASE_NAME}
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://${APP_SERVER_HOST}:8761/eureka

logging:
  file:
    name: logs/user-service.log