server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://${APP_SERVER_HOST}:8761/eureka
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    name: logs/service-discovery-server.log